# COGS 108 - Final Project

# Overview

For this project, I analyzed the provided datasets in order to answer my research question. I used one of the provided datasets and cleaned the data. After this, I compared the datasest with each other in the data analysis section.

# Name & GitHub

- Name: Shirley Dinh
- GitHub Username: s4dinh

# Research Question

Does the size of a restaurant affect its health grade? Would mobile eateries on average typically have lower health grades than brick and mortar restaurants due to its confined nature?

## Background and Prior Work

After conducting some research on health inspections in Los Angeles County (L.A. County), I found that brick and mortar restaurants are inspected 1-3 times a year while food trucks are inspected 1-2 times a year. This could be due the fact that brick and mortar restaurants have a set location while food trucks constantly move around and it would be difficult to track them down. In addition to this, according to public health food safety and regulations in L.A. County, food trucks are held to basically the same standard as brick and mortar restaurants despite the environmental and size differences.

According to an article on Fox News in 2016, about 30% of L.A. food trucks earned a health grade lower than A, while about 18% of brick and mortar restaurants earned a health grade lower than A. It mentioned that “Workers make food in a confined space (“typically less than 8 feet wide by 20 feet long,” according to the paper) and trucks don’t usually have as much equipment as a full size restaurant, which can lead to cross-contamination.”

Another reference that I found online is a case study on food regulations for food trucks in U.S. cities. The case study discusses the varying challenges of facing food safety measures across cities in the U.S., such as Chicago, and New York City. I think this case study will be very relevant for my research question.

References (include links):

1)https://www.foxnews.com/food-drink/nearly-30-percent-of-los-angeles-food-trucks-face-sanitation-problems-report-finds
2)https://datasmart.ash.harvard.edu/news/article/case-study-food-trucks-585

# Hypothesis

I hypothesize that the smaller a restaurant is (calculated in square feet or capacity), the higher chance that it will have a lower health grade. In particular, food trucks have a higher risk of receiving a lower health grade due to higher risk of cross contamination and cross contact.

# Dataset(s)

*Fill in your dataset information here*

(Copy this information for each dataset)
- Dataset Name: inspections.csv
- Link to the dataset:
- Number of observations: 

1-2 sentences describing each dataset. 

This is one the provided datasets describing the inspections of multiple eateries.

If you plan to use multiple datasets, add 1-2 sentences about how you plan to combine these datasets.

-Dataset Name:

# Setup

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Data Cleaning

Describe your data cleaning steps here.

In [2]:
df_inspections = pd.read_csv('inspections.csv')
df_inspections = df_inspections.drop(['date', 'address1', 'address2', 'city', 'state', 'postalcode', 'phonenumber', 'restaurantopendate', 'days_from_open_date', 'x', 'y', 'geocodestatus', 'zip', 'type', 'inspectedby', 'inspection_num', 'inspector_id', 'previous_inspection_date', 'days_since_previous_inspection', 'previous_inspection_by_same_inspector'], axis = 1)
df_inspections

,hsisid,name,facilitytype,description,score,num_critical,num_non_critical,num_critical_previous,num_non_critical_previous,num_critical_mean_previous,num_non_critical_mean_previous,avg_neighbor_num_critical,avg_neighbor_num_non_critical,top_match,second_match,critical
0,4092013748,Cafe 3000 At Wake Med,Restaurant,This facility cooks eggs to order in Grill sta...,96.0,9,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,4092014046,Overtime Sports Pub,Restaurant,NaN,98.0,0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,4092015191,TASTE OF CHINA,Restaurant,NaN,97.0,4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,4092016122,Panera Bread #1643,Restaurant,NaN,99.0,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4092021513,WalMart Supercenter #4499-00 Deli/Bakery,Food Stand,"New rules, www.wakegov.com/food",97.0,2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18461,4092021142,Sino Wok,Food Stand,NaN,93.0,6,13,1.0,4.0,1.000000,4.777778,4.692525,9.863838,4.092022e+09,4.092017e+09,1
18462,4092110100,Weatherstone Elem. Sch. Cafeteria,Public School Lunchrooms,NaN,97.0,2,3,2.0,5.0,0.750000,3.250000,5.853333,5.972381,4.092013e+09,4.092016e+09,1
18463,4092110487,ALSTON RIDGE ELEMENTARY SCHOOL CAFETERIA,Public School Lunchrooms,NaN,96.0,3,4,0.0,2.0,0.875000,1.750000,2.466667,3.000000,4.092017e+09,4.092015e+09,1
18464,4092300177,Food Lion #996 Meat Market,Meat Market,NaN,99.0,1,2,0.0,3.0,1.111111,2.000000,3.737302,4.606349,4.092016e+09,4.092015e+09,1
18465,4092300225,LA CAMPANA MARKET,Meat Market,Inspector contact info: Dimitri Parker (919)86...,93.0,4,7,5.0,8.0,4.250000,6.375000,2.048810,3.235714,4.092016e+09,4.092015e+09,1

In [3]:
df_type_restaurants = df_inspections[df_inspections['facilitytype'] == 'Restaurant']
df_type_restaurants

,hsisid,name,facilitytype,description,score,num_critical,num_non_critical,num_critical_previous,num_non_critical_previous,num_critical_mean_previous,num_non_critical_mean_previous,avg_neighbor_num_critical,avg_neighbor_num_non_critical,top_match,second_match,critical
0,4092013748,Cafe 3000 At Wake Med,Restaurant,This facility cooks eggs to order in Grill sta...,96.0,9,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,4092014046,Overtime Sports Pub,Restaurant,NaN,98.0,0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,4092015191,TASTE OF CHINA,Restaurant,NaN,97.0,4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,4092016122,Panera Bread #1643,Restaurant,NaN,99.0,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
6,4092013134,Pearl Chinese Restaurant,Restaurant,NaN,96.0,6,7,NaN,NaN,NaN,NaN,3.000000,6.400000,4.092014e+09,4.092016e+09,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18453,4092015590,ARCHIBALD`S TAVERN,Restaurant,NaN,93.5,2,7,11.0,4.0,5.000000,5.500000,4.579798,6.629798,4.092016e+09,4.092015e+09,1
18454,4092016479,THE OVAL,Restaurant,"At the dish washing sink, the quat sanitizer i...",97.0,3,6,1.0,3.0,1.714286,2.000000,1.766580,5.537316,4.092022e+09,4.092011e+09,1
18455,4092016866,AWAZ'E ETHIOPIAN/ERITREAN CUISINE,Restaurant,Follow-Up: 11/13/2016,97.0,3,5,0.0,6.0,4.000000,5.750000,3.035556,8.104444,4.092016e+09,4.092300e+09,1
18456,4092016949,TAVERNA AGORA,Restaurant,NaN,96.0,3,6,5.0,2.0,4.333333,1.333333,3.864286,6.834524,4.092012e+09,4.092016e+09,1
18457,4092017172,NEWK'S EATERY #1107,Restaurant,NaN,95.0,4,3,3.0,4.0,3.000000,4.000000,1.295238,4.317143,4.092010e+09,4.092014e+09,1

In [4]:
df_type_mobile = df_inspections[df_inspections['facilitytype'] == 'Mobile Food Units']
df_type_mobile

,hsisid,name,facilitytype,description,score,num_critical,num_non_critical,num_critical_previous,num_non_critical_previous,num_critical_mean_previous,num_non_critical_mean_previous,avg_neighbor_num_critical,avg_neighbor_num_non_critical,top_match,second_match,critical
197,4092030237,RED EYE BARBECUE (WCID #416),Mobile Food Units,BRISKET-OVEN-142-155F\r\nPORK BUTT-OVEN-198F\r...,96.0,5,5,NaN,NaN,NaN,NaN,6.600000,7.200000,4.092110e+09,4.092014e+09,1
298,4092030175,DON BETO EL POBLANO (WCID #482),Mobile Food Units,Cold holding temperature requirement for poten...,98.0,1,6,NaN,NaN,NaN,NaN,5.400000,10.000000,4.092016e+09,4.092012e+09,1
315,4092030220,EL REY DEL TACO (WCID #376),Mobile Food Units,NaN,93.5,9,4,NaN,NaN,NaN,NaN,6.200000,8.000000,4.092016e+09,4.092012e+09,1
316,4092030232,HIBACHI XPRESS (WCID #396),Mobile Food Units,NaN,95.5,6,5,NaN,NaN,NaN,NaN,4.000000,9.400000,4.092016e+09,4.092011e+09,1
356,4092030207,TACOS CAMPA (WCID #353),Mobile Food Units,3-603.11 Consumption of Animal Foods that are ...,98.0,4,3,NaN,NaN,NaN,NaN,4.000000,8.200000,4.092300e+09,4.092016e+09,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18099,4092030293,"ZEKE'S MEATS, LLC (WCID #544)",Mobile Food Units,"Inspection conducted by Marion Wearing, EHSI #...",98.5,3,2,0.0,4.0,2.500000,3.500,2.700000,1.500000,4.092040e+09,4.092040e+09,1
18303,4092030207,TACOS CAMPA (WCID #353),Mobile Food Units,NaN,98.0,1,3,0.0,3.0,2.333333,2.500,4.660952,7.433651,4.092013e+09,4.092015e+09,1
18346,4092030223,Valentino`s (WCID 378),Mobile Food Units,Verification required for Item #46 on this rep...,90.0,8,6,2.0,2.0,1.400000,3.000,3.149444,8.438889,4.092016e+09,4.092011e+09,1
18389,4092030234,CHICK-N-QUE II (WCID #425),Mobile Food Units,NaN,98.5,0,4,0.0,3.0,2.250000,2.875,1.915714,4.555714,4.092020e+09,4.092022e+09,0
18442,4092030195,Specialty South DBA Wicked Links (WCID #225),Mobile Food Units,NaN,99.5,0,1,0.0,1.0,1.500000,1.500,1.908333,3.333333,4.092012e+09,4.092021e+09,0

I took the inspections.csv data and cleaned the data by separating into two separate dataframes, one being just restaurants, and the other of only mobile food units. I also drooped any column that I felt were irrelevant to my research question.

# Data Analysis & Results

Include cells that describe the steps in your data analysis.

In [70]:
## YOUR CODE HERE
df_type_restaurants['score'].mean()

95.66558197747185

In [71]:
df_type_mobile['score'].mean()

97.11267605633803

# Ethics & Privacy

# Conclusion & Discussion

Although